@startuml


' avoid problems with angled crows feet
skinparam linetype ortho

entity "NewCustomer" as nc {
  id : varchar
  --
  status_id : varchar
  closedAt: date -- 成約した日付が入る
}

entity "NewCustomerActiveityHistory" as ncah {
  id : varchar
  --
  activity_id : varchar
  actedAt: date 行動した日付
}

entity "ActivityMaster" as am {
  id : varchar
  --
  name : varchar
}

entity "StatusMaster" as sm {
  id : varchar
  --
  name : varchar
}


nc ||..o{ ncah
am ||..o{ ncah
sm ||..o{ nc
@enduml
