@startuml

agent プレゼンテーション層

card プレゼンテーション層役割 [
エンドポイント定義
....
Http Requestで渡された値とユースケースそうに渡す値のマッピング
....
入力値のvalidation(一部)
....
JSONでレスポンスを返したり、HTMLをレンダリングしてユーザインターフェイスを出力する
]

agent ユースケース層

card ユースケース層役割 [
アプリケーション層とも言われる
....
ドメインオブジェクトの生成、使用、永続化依頼
....
ドメインオブジェクトからプレゼンテーション層に渡す値への変換
]

agent ドメイン層

card ドメイン層役割 [
ドメインオブジェクト(エンティティ、値オブジェクト)-ドメイン知識(ルール/制約)の表現
....
ドメインサービス
....
リポジトリ(インターフェイス):リポジトリの仕様定義
....
ここをドメインモデル層とドメインサービス層で分ける方法もある
]

agent インフラ層

card インフラ層役割 [
リポジトリ(実装クラス)：-ドメインオブジェクトの永続化/検索の実装
]


プレゼンテーション層 -- プレゼンテーション層役割
ユースケース層 -- ユースケース層役割
ドメイン層 -- ドメイン層役割
インフラ層役割 -- インフラ層
プレゼンテーション層 --> ユースケース層 : 使用
ユースケース層 --> ドメイン層 : 使用
インフラ層 --^ ドメイン層 : インターフェイスの実装
インフラ層 --^ ユースケース層 : インターフェイスの実装

@enduml
