name : lint-test
on:
  pull_request:
defaults:
  run:
    #frontend/praha-challenge-front-appで動かす
    working-directory: frontend/praha-challenge-front-app
jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup
        uses: actions/setup-node@v3
      - name: cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
      - name: yarn lint
      - run: yarn
      - run: yarn lint